#!/usr/bin/env zsh

set -e
set -o pipefail

tag=docker-compilation-images-hello-world

dir=$(cd $(dirname $0)/.. && pwd)
cd $dir

./docker-build --tag=run=$tag test/hello-world
expected=$(echo -e 'Hello, world!\r\n')
actual=$(docker run --rm --interactive --tty $tag)
echo
[[ $expected == $actual ]] && echo 'Test passed.' || {
    echo 'Test failed.'
    echo 'Expected output:'
    hexdump -C <<< $expected
    echo 'Actual output:'
    hexdump -C <<< $actual
}
